version: '3.8'

services:
  # MongoDB база данных
  mongo:
    image: mongo:6.0
    container_name: herzen-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: herzen123
      MONGO_INITDB_DATABASE: herzen
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - herzen-network

  # Redis (опционально)
  redis:
    image: redis:7-alpine
    container_name: herzen-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - herzen-network

  # Herzen Core приложение
  herzen-core:
    build: .
    container_name: herzen-core
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    environment:
      NODE_ENV: production
      PORT: 8118
    ports:
      - "80:8118"
    volumes:
      - herzen_data:/app/data
      - herzen_logs:/app/logs
      - herzen_uploads:/app/public/uploads
    networks:
      - herzen-network


volumes:
  mongo_data:
  herzen_data:
  herzen_logs:
  herzen_uploads:

networks:
  herzen-network:
    driver: bridge